import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,realpathSync,rmSync,symlinkSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {gunzipSync,gzipSync} from 'node:zlib';
import {writeProductWebArchive} from '../../builder/scripts/product-release.ts';
import {createWebProbes} from '../../builder/scripts/product-web.ts';
import {packages} from '../../builder/scripts/npm-release.ts';
import type {ProductIdentity} from '../../builder/scripts/product-identity.ts';
import type {ArtifactProof,ProductManifest,ProductPackageReceipt} from '../../builder/scripts/release-types.ts';
import {parseSealedWebArguments,qualifySealedWeb,withSealedWebExtraction} from './sealed-web.ts';

const source='a'.repeat(40);
const identity:ProductIdentity={schema:1,version:'0.3.1',tag:'v0.3.1',sourceCommit:source,sourceFingerprint:'sha256:'+'b'.repeat(64)};
const digest=(bytes:Buffer,algorithm='sha256')=>createHash(algorithm).update(bytes).digest('hex');
function object(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==='object'&&!Array.isArray(value);}
/** Tiny real tar/gzip transports and exact checksums, deliberately NOT an
 * installed SQLite/runtime or accepted-browser fixture. Browser preflight fails. */
async function fixture(){
  const owned=mkdtempSync(path.join(realpathSync(tmpdir()),'sealed-web-contract-')),bundle=path.join(owned,'bundle'),web=path.join(owned,'web');mkdirSync(bundle);mkdirSync(web);
  const put=(root:string,file:string,bytes:string|Buffer)=>{mkdirSync(path.dirname(path.join(root,file)),{recursive:true});writeFileSync(path.join(root,file),bytes);};
  const database=Buffer.from('Transport-only SQLite bytes; not an accepted database.\n');const sidecar=JSON.stringify({sha256:'sha256:'+digest(database),snapshot:{source_commit:source,content_version:identity.version}});
  put(bundle,'library.sqlite',database);put(bundle,'library.sqlite.json',sidecar);
  const counts={pcrs:1,pages:2,languages:2,sourceBytes:1};
  for(const file of ['index.html','zh/index.html','en/index.html','en/docs/pcr/index.html','zh/docs/pcr/index.html'])put(web,file,'<h1>Transport fixture</h1>');
  put(web,'generated/product-release.json',JSON.stringify(identity));put(web,'generated/version.json',JSON.stringify({releaseVersion:identity.version,releaseTag:identity.tag,sourceCommit:source,sourceFingerprint:identity.sourceFingerprint,counts}));put(web,'edgeone.json','{}');put(web,'generated/raw/classifications/indexes/cpc-3.0-coverage.json','{}');
  const receipts:Partial<Record<'tool'|'library',ProductPackageReceipt>>={};
  for(const kind of ['tool','library'] as const){const packageRoot=path.join(owned,kind);mkdirSync(packageRoot);put(packageRoot,'package/product-release.json',JSON.stringify(identity));put(packageRoot,'package/package.json',JSON.stringify({name:packages[kind].name,version:identity.version,gitHead:source}));if(kind==='library'){put(packageRoot,'package/library.sqlite',database);put(packageRoot,'package/library.sqlite.json',sidecar);}const filename=(packages[kind].name+'-'+identity.version+'.tgz').replace(/^@/u,'').replaceAll('/','-');await writeProductWebArchive(packageRoot,path.join(bundle,filename));const bytes=readFileSync(path.join(bundle,filename));receipts[kind]={filename,bytes:bytes.length,sha256:digest(bytes),name:packages[kind].name,version:identity.version,tag:identity.tag,sourceCommit:source,integrity:'sha512-'+createHash('sha512').update(bytes).digest('base64')};}
  const filename='pcr-web-'+identity.version+'.tar.gz',archive=await writeProductWebArchive(web,path.join(bundle,filename)),bytes=readFileSync(path.join(bundle,filename));
  const proof=(name:string):ArtifactProof=>{const bytes=readFileSync(path.join(bundle,name));return{filename:name,bytes:bytes.length,sha256:digest(bytes)};};
  const webArtifact={filename,bytes:bytes.length,sha256:digest(bytes),files:archive.files,uncompressedBytes:archive.uncompressedBytes,treeSha256:archive.treeSha256,origin:'https://pcr.tiangong.earth',probes:createWebProbes({webDir:web})};
  const tool=receipts.tool,library=receipts.library;assert.ok(tool&&library);
  const manifest:ProductManifest={schema:1,kind:'pcr-product-release',identity,toolchain:{node:'24.19.0',npm:'12.2.0'},packages:{tool,library},web:webArtifact,artifacts:[proof(tool.filename),proof(library.filename),proof('library.sqlite'),proof('library.sqlite.json'),proof(filename)]};
  put(bundle,'release.json',JSON.stringify(manifest));const checksums=[...manifest.artifacts,proof('release.json')].sort((a,b)=>a.filename<b.filename?-1:1).map(file=>file.sha256+'  '+file.filename+'\n').join('');put(bundle,'SHA256SUMS',checksums);
  const before=()=>Object.fromEntries(readdirSync(bundle).sort().map(name=>[name,digest(readFileSync(path.join(bundle,name)))]));
  return {owned,bundle,manifest,before,close(){rmSync(owned,{recursive:true,force:true});}};
}

test('sealed web requires an explicit bundle report and full source without silent fallback',()=>{assert.equal(parseSealedWebArguments(['--help']),'help');for(const args of [[],['--bundle','x'],['--bundle','x','--report','y'],['--bundle','x','--report','y','--expected-source','short'],['--bundle','x','--report','y','--expected-source','0'.repeat(40)],['--bundle','x','--report','y','--expected-source',source,'--bundle','z']])assert.throws(()=>parseSealedWebArguments(args),{code:'SEALED_WEB_ARGUMENT'});assert.deepEqual(parseSealedWebArguments(['--bundle','x','--report','y','--expected-source',source]),{root:path.resolve('x'),report:path.resolve('y'),expectedSource:source});});
test('missing bundles fail explicitly before allocating browser or extraction resources',async()=>{const root=mkdtempSync(path.join(realpathSync(tmpdir()),'sealed-web-missing-'));try{await assert.rejects(withSealedWebExtraction({root:path.join(root,'absent'),expectedSource:source},async()=>{assert.fail('Missing input cannot reach callback.');}),{code:'SEALED_WEB_INPUT'});}finally{rmSync(root,{recursive:true,force:true});}});
test('source mismatch rejects otherwise sealed input without modifying its bytes',async()=>{const f=await fixture();try{const before=f.before();await assert.rejects(withSealedWebExtraction({root:f.bundle,expectedSource:'c'.repeat(40)},async()=>{assert.fail('Mismatched source cannot reach extraction.');}),{code:'SEALED_WEB_SOURCE_MISMATCH'});assert.deepEqual(f.before(),before);}finally{f.close();}});
test('corrupt sealed archive fails its actual checksum before extraction callback',async()=>{const f=await fixture();try{writeFileSync(path.join(f.bundle,f.manifest.web.filename),'not a gzip archive');let called=false;await assert.rejects(withSealedWebExtraction({root:f.bundle,expectedSource:source},async()=>{called=true;}),/checksum differs/u);assert.equal(called,false);}finally{f.close();}});
test('even rehashed hostile archive paths cannot escape verified extraction',async()=>{const f=await fixture();try{const filename=path.join(f.bundle,f.manifest.web.filename),tar=gunzipSync(readFileSync(filename));tar.fill(0,0,100);tar.write('../escaped.txt',0,'ascii');tar.fill(32,148,156);const sum=tar.subarray(0,512).reduce((total,byte)=>total+byte,0);tar.write(sum.toString(8).padStart(6,'0')+'\0 ',148,8,'ascii');const bytes=gzipSync(tar);writeFileSync(filename,bytes);f.manifest.web.bytes=bytes.length;f.manifest.web.sha256=digest(bytes);const webProof=f.manifest.artifacts.find(proof=>proof.filename===f.manifest.web.filename);assert.ok(webProof);webProof.bytes=bytes.length;webProof.sha256=digest(bytes);writeFileSync(path.join(f.bundle,'release.json'),JSON.stringify(f.manifest));const manifestBytes=readFileSync(path.join(f.bundle,'release.json'));const sums=[...f.manifest.artifacts,{filename:'release.json',bytes:manifestBytes.length,sha256:digest(manifestBytes)}].sort((a,b)=>a.filename<b.filename?-1:1).map(proof=>proof.sha256+'  '+proof.filename+'\n').join('');writeFileSync(path.join(f.bundle,'SHA256SUMS'),sums);await assert.rejects(withSealedWebExtraction({root:f.bundle,expectedSource:source},async()=>{assert.fail('Hostile archive cannot reach callback.');}),/Unsafe archive path/u);assert.equal(existsSync(path.join(f.owned,'escaped.txt')),false);}finally{f.close();}});
test('verified extraction returns exact sealed files and cleans owned materialization on success',async()=>{const f=await fixture();let extracted='';try{const before=f.before();const result=await withSealedWebExtraction({root:f.bundle,expectedSource:source,expectedIdentity:identity},async web=>{extracted=web.directory;assert.equal(web.tree.treeSha256,f.manifest.web.treeSha256);assert.equal(web.manifest.identity.sourceCommit,source);assert.equal(readFileSync(path.join(web.directory,'index.html'),'utf8'),'<h1>Transport fixture</h1>');return web.tree.files;});assert.equal(result,f.manifest.web.files);assert.equal(existsSync(extracted),false);assert.equal(existsSync(path.dirname(extracted)),false);assert.deepEqual(f.before(),before);}finally{f.close();}});
test('callback failure including thrown undefined preserves inputs and cleans extraction',async()=>{const f=await fixture();try{const before=f.before();for(const reason of [new Error('Expected callback failure'),undefined]){let extracted='';let rejected=false;try{await withSealedWebExtraction({root:f.bundle,expectedSource:source},async web=>{extracted=web.directory;throw reason;});}catch(error){rejected=true;assert.equal(error,reason);}assert.ok(rejected);assert.equal(existsSync(extracted),false);}assert.deepEqual(f.before(),before);}finally{f.close();}});
test('external input mutation during scoped extraction is detected before a successful return',async()=>{const f=await fixture();let extracted='';try{await assert.rejects(withSealedWebExtraction({root:f.bundle,expectedSource:source},async web=>{extracted=web.directory;writeFileSync(path.join(f.bundle,'SHA256SUMS'),'substituted input');}),{code:'SEALED_WEB_INPUT_CHANGED'});assert.equal(existsSync(extracted),false);}finally{f.close();}});
test('prior report directories and report aliases inside the bundle are never replaced',async()=>{const f=await fixture();try{const report=path.join(f.owned,'prior');mkdirSync(report);writeFileSync(path.join(report,'keep.txt'),'prior evidence');await assert.rejects(qualifySealedWeb({root:f.bundle,expectedSource:source,report}));assert.equal(readFileSync(path.join(report,'keep.txt'),'utf8'),'prior evidence');const alias=path.join(f.owned,'bundle-alias');symlinkSync(f.bundle,alias,'dir');await assert.rejects(qualifySealedWeb({root:f.bundle,expectedSource:source,report:path.join(alias,'report')}));assert.equal(existsSync(path.join(f.bundle,'report')),false);}finally{f.close();}});
test('real browser preflight failure retains failed evidence and proves extraction cleanup without fake acceptance',async()=>{const f=await fixture();try{const report=path.join(f.owned,'report'),before=f.before();await assert.rejects(qualifySealedWeb({root:f.bundle,expectedSource:source,report}),/Missing required exported input/u);const value:unknown=JSON.parse(readFileSync(path.join(report,'qualification.json'),'utf8'));assert.ok(object(value));assert.equal(value.status,'failed');assert.equal(value.immutableInputVerified,true);assert.equal(value.extractionRemoved,true);assert.equal(value.browserCases,undefined);assert.equal(value.browserReport,undefined);assert.equal(value.identity!==undefined,true);assert.deepEqual(f.before(),before);}finally{f.close();}});
